name: limma_env
channels:
  - bioconda
  - conda-forge
dependencies:
  - bioconductor-limma=3.58.1
  - bioconductor-edger=4.0.16
  - bioconductor-goseq
  - bioconductor-genelendatabase
  - r-optparse
  - r-tidyverse
  - r-ggrepel
